spring.application.name: s3-demo
# swagger-ui custom path
springdoc.swagger-ui.path: /swagger-ui.html

storage:
  type: s3
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
